# Generated by Django 5.0.6 on 2024-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
