version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nest
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
